"""emotion field added to dialog table

Revision ID: b15129a55e02
Revises: 226b7f99efed
Create Date: 2025-06-09 21:09:04.144378

"""
import sqlmodel
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b15129a55e02'
down_revision: Union[str, None] = '226b7f99efed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dialog', sa.Column('emotion', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dialog', 'emotion')
    # ### end Alembic commands ###
