"""change from turn to section attrib.

Revision ID: 384755743eee
Revises: 65256934b21a
Create Date: 2025-05-02 19:23:30.312727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '384755743eee'
down_revision: Union[str, None] = '65256934b21a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('current_section', sa.Integer(), default=100))
    op.drop_column('chat', 'current_turn')
    op.add_column('dialog', sa.Column('section', sa.Integer(), default=100))
    op.drop_column('dialog', 'turn')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dialog', sa.Column('turn', sa.INTEGER(), nullable=False))
    op.drop_column('dialog', 'section')
    op.add_column('chat', sa.Column('current_turn', sa.INTEGER(), nullable=False))
    op.drop_column('chat', 'current_section')
    # ### end Alembic commands ###
