"""remove history from chat

Revision ID: 65256934b21a
Revises: 6355c8b832a0
Create Date: 2025-04-29 22:53:57.841349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '65256934b21a'
down_revision: Union[str, None] = '6355c8b832a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'history')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('history', sa.VARCHAR(length=10000), nullable=False))
    # ### end Alembic commands ###
